site_name: zephyr.space
site_url: https://zephyr.space/
repo_url: https://github.com/uwoseis/zephyr/
site_description: an open-source seismic FWI toolkit
site_author: Brendan Smithyman
copyright: © 2014–2015 Brendan Smithyman
pages:
- Intro: index.md
- Background: background.md
- About: about.md
theme: flatly
markdown_extensions:
- abbr
- codehilite
- def_list
- footnotes
- markdown_include.include:
    base_path: docs/
- math:
    enable_dollar_delimiter: True
extra_javascript:
- 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
- 'scripts/mathjaxhelper.js'