site_name: zephyr.space
site_url: https://zephyr.space/
repo_url: https://github.com/bsmithyman/zephyr/
site_description: an open-source seismic FWI toolkit
site_author: Brendan Smithyman
copyright: © 2014 Brendan Smithyman
pages:
- Intro: index.md
- About: about.md
theme: united